USE Gestion_Universitaria

GO

-- Insertar datos en la tabla Administrativos
INSERT INTO Administrativos (nombre, apellido, telefono, email) VALUES
('Mario', 'Pérez', '11-1234-5678', 'mario.perez@universidad.edu'),
('María', 'López', '11-2345-6789', 'maria.lopez@universidad.edu'),
('Carlos', 'García', '11-3456-7890', 'carlos.garcia@universidad.edu'),
('Laura', 'Martínez', '11-4567-8901', 'laura.martinez@universidad.edu'),
('Juan', 'Rodríguez', '11-5678-9012', 'juan.rodriguez@universidad.edu'),
('Ana', 'Fernández', '11-6789-0123', 'ana.fernandez@universidad.edu'),
('José', 'Gómez', '11-7890-1234', 'jose.gomez@universidad.edu'),
('Luis', 'Díaz', '11-8901-2345', 'luis.diaz@universidad.edu'),
('Sofía', 'Muñoz', '11-9012-3456', 'sofia.munoz@universidad.edu'),
('Miguel', 'Sánchez', '11-0123-4567', 'miguel.sanchez@universidad.edu'),
('Elena', 'Torres', '11-1234-5678', 'elena.torres@universidad.edu'),
('Diego', 'Vargas', '11-2345-6789', 'diego.vargas@universidad.edu'),
('Marta', 'Castro', '11-3456-7890', 'marta.castro@universidad.edu'),
('Pedro', 'Ramos', '11-4567-8901', 'pedro.ramos@universidad.edu'),
('Patricia', 'Reyes', '11-5678-9012', 'patricia.reyes@universidad.edu'),
('Ricardo', 'Ruiz', '11-6789-0123', 'ricardo.ruiz@universidad.edu'),
('Verónica', 'Ortiz', '11-7890-1234', 'veronica.ortiz@universidad.edu'),
('Daniel', 'Medina', '11-8901-2345', 'daniel.medina@universidad.edu'),
('Sandra', 'Iglesias', '11-9012-3456', 'sandra.iglesias@universidad.edu'),
('Alberto', 'Santos', '11-0123-4567', 'alberto.santos@universidad.edu');


INSERT INTO Aulas (nombre, capacidad) VALUES
('Aula 101', 30),
('Aula 102', 40),
('Aula 103', 50),
('Aula 104', 35),
('Aula 105', 25),
('Aula 106', 45),
('Aula 107', 55),
('Aula 108', 60),
('Aula 109', 20),
('Aula 110', 70),
('Aula 201', 30),
('Aula 202', 40),
('Aula 203', 50),
('Aula 204', 35),
('Aula 205', 25),
('Aula 206', 45),
('Aula 207', 55),
('Aula 208', 60),
('Aula 209', 20),
('Aula 210', 70);


INSERT INTO Carreras (Nombre, descripcion) VALUES
('Ingeniería Civil', 'Carrera de grado - Ingenieria civil'),
('Ingeniería Informática', 'Carrera de grado - Ingenieria en informatica'),
('Medicina', 'Carrera de grado - Medico'),
('Derecho', 'Carrera de grado - Abogacia'),
('Psicología', 'Carrera de grado - Licenciatura en Psicologia'),
('Administración de Empresas', 'Carrera de grado - Licenciatura en Administracion de empresas'),
('Contabilidad', 'Carrera de grado - Contador Publico'),
('Arquitectura', 'Carrera de grado - Arquitectura'),
('Diseño Gráfico', 'Carrera de grado - Licenciatura en Diseño Grafico'),
('Comunicación Social', 'Carrera de grado - Licenciatura en Comunicación Social'),
('Relaciones Internacionales', 'Carrera de grado - Licenciatura en Relaciones Internacionales'),
('Educación', 'Carrera de grado - Licenciatura en Educacion'),
('Biología', 'Carrera de grado - Licenciatura en Biologia molecular'),
('Química', 'Carrera de grado - Licenciatura en Quimica organica'),
('Física', 'Carrera de grado - Licenciatura en Fisica'),
('Matemáticas', 'Carrera de grado - Profesorado de Matematicas'),
('Filosofía', 'Carrera de grado - Licenciatura en Filosofia'),
('Historia', 'Carrera de grado - Profesorador en Historia'),
('Geografía','Carrera de grado - Profesorador en Geografia'),
('Literatura', 'Carrera de grado - Profesorador en Literatura')

INSERT INTO Profesores (Nombre, Apellido, email, FechaNacimiento, Sexo) VALUES
('Pablo', 'Fernández', 'pablo.fernandez@universidad.edu', '1990-12-03', 'M'),
('Sofía', 'González', 'sofia.gonzalez@universidad.edu', '1985-12-02', 'F'),
('Martín', 'Pérez', 'martin.perez@universidad.edu', '1978-04-08', 'M'),
('Lucía', 'López', 'lucia.lopez@universidad.edu', '1978-03-06', 'F'),
('Carlos', 'García', 'carlos.garcia@universidad.edu', '1968-11-07', 'M'),
('Valentina', 'Martínez', 'valentina.martinez@universidad.edu', '1999-02-07', 'F'),
('Francisco', 'Rodríguez', 'francisco.rodriguez@universidad.edu', '2000-01-11', 'M'),
('Marta', 'Sánchez', 'marta.sanchez@universidad.edu', '1993-11-11', 'F'),
('Diego', 'Ramírez', 'diego.ramirez@universidad.edu', '1987-09-08', 'M'),
('Julia', 'Torres', 'julia.torres@universidad.edu', '1965-10-07', 'F'),
('Andrés', 'Romero',  'andres.romero@universidad.edu', '1991-12-10', 'M'),
('Camila', 'Díaz', 'camila.diaz@universidad.edu', '1998-12-12', 'F'),
('Pedro', 'Vega', 'pedro.vega@universidad.edu', '2001-11-05' , 'M'),
('Carolina', 'Ortiz', 'carolina.ortiz@universidad.edu', '1992-10-06' , 'F'),
('Gabriel', 'Gómez', 'gabriel.gomez@universidad.edu', '1975-02-05' , 'M'),
('Mariana', 'Ruiz', 'mariana.ruiz@universidad.edu', '1988-06-12' , 'F'),
('Nicolás', 'Álvarez', 'nicolas.alvarez@universidad.edu', '2005-05-05', 'M'),
('Laura', 'Benítez', 'laura.benitez@universidad.edu', '1985-04-11' , 'F'),
('Javier', 'Muñoz', 'javier.munoz@universidad.edu', '1965-09-19', 'M'),
('Gloria', 'Navarro', 'gloria.navarro@universidad.edu', '1991-05-12', 'F');

INSERT INTO Estudiantes (nombre, apellido, email, FechaNacimiento, Sexo) VALUES
('Juan Manuel', 'Aguilar', 'juan.manuel.aguilar@gmail.com', '1988-05-12', 'M'),
('María', 'López', 'maria.lopez@yahoo.com', '1991-08-22', 'F'),
('Carlos', 'García', 'carlos.garcia@hotmail.com', '1992-03-10', 'M'),
('Lucía', 'Martínez', 'lucia.martinez@gmail.com', '1993-11-25', 'F'),
('Pablo', 'González', 'pablo.gonzalez@yahoo.com', '1994-01-14', 'M'),
('Sofía', 'Rodríguez', 'sofia.rodriguez@hotmail.com', '1995-06-30', 'F'),
('Martín', 'Fernández', 'martin.fernandez@gmail.com', '1996-09-17', 'M'),
('Ana', 'Gómez', 'ana.gomez@yahoo.com', '1997-12-05', 'F'),
('Miguel', 'Díaz', 'miguel.diaz@hotmail.com', '1998-04-22', 'M'),
('Laura', 'Sánchez', 'laura.sanchez@gmail.com', '1999-07-10', 'F'),
('David', 'Ramírez', 'david.ramirez@yahoo.com', '2000-10-03', 'M'),
('Elena', 'Torres', 'elena.torres@hotmail.com', '2001-02-19', 'F'),
('Diego', 'Vargas', 'diego.vargas@gmail.com', '1990-06-15', 'M'),
('Marta', 'Castro', 'marta.castro@yahoo.com', '1991-09-27', 'F'),
('Luis', 'Reyes', 'luis.reyes@hotmail.com', '1992-12-09', 'M'),
('Patricia', 'Ruiz', 'patricia.ruiz@gmail.com', '1993-03-21', 'F'),
('Javier', 'Romero', 'javier.romero@yahoo.com', '1994-07-30', 'M'),
('Verónica', 'Ortiz', 'veronica.ortiz@hotmail.com', '1995-10-18', 'F'),
('Ricardo', 'Núñez', 'ricardo.nunez@gmail.com', '1996-01-05', 'M'),
('Sandra', 'Iglesias', 'sandra.iglesias@yahoo.com', '1997-04-14', 'F');
